### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by vermiculus** [ksjogo/emacs-libgit2#1]
Does emacs-libgit2 need to be linked build-time or does it need to be
dropped in some special folder?  If the former, how should emacs be
built?

This information would be very useful to have in the README :smile:

I'd love to help develop this tool, but I'm unclear on how to start.

**Comment by ksjogo** [comment]
The folder needs to be in the load-path and then you can require as usual.
I will merge the existing additions in the other fork, look into Windows building and then add more README stuff.

**Comment by vermiculus** [comment]
For instance, `make` fails:

```
~/github/emacs-libgit2 $ make
mkdir -p libgit2/build
cd libgit2/build
[ ! -d CMakeFiles ] && cmake -DBUILD_SHARED_LIBS=OFF -DTHREADSAFE=ON -DBUILD_CLAR=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE="RelWithDebInfo" ..
CMake Error: The source directory "/Users/sean/github" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [libgit2] Error 1
```

**Comment by ksjogo** [comment]
That is (probably) caused by the old mac make version not supporting .ONESHELL. gmake would fix that for the moment.

**Comment by ksjogo** [comment]
Could you try the new cmake build?

**Comment by vermiculus** [comment]
CMake works, but alas, no luck in actually requiring the feature 😦 

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "libgit2-core")
  require(libgit2-core)
  eval-buffer(#<buffer  *load*> nil "/Users/sean/github/emacs-libgit2/libgit2.el" nil t)  ; Reading at buffer position 304
  load-with-code-conversion("/Users/sean/github/emacs-libgit2/libgit2.el" "/Users/sean/github/emacs-libgit2/libgit2.el" nil t)
  require(libgit2)
  (let ((load-path (cons "/Users/sean/github/emacs-libgit2" load-path))) (require (quote libgit2)))
  eval((let ((load-path (cons "/Users/sean/github/emacs-libgit2" load-path))) (require (quote libgit2))) nil)
  pp-eval-expression((let ((load-path (cons "/Users/sean/github/emacs-libgit2" load-path))) (require (quote libgit2))))
  pp-eval-last-sexp(nil)
  funcall-interactively(pp-eval-last-sexp nil)
  call-interactively(pp-eval-last-sexp nil nil)
  command-execute(pp-eval-last-sexp)
```

**Comment by ksjogo** [comment]
Do you have an emacs-25 configured with '--with-modules'?

**Comment by vermiculus** [comment]
Hmm, I have the build from [emacsformacosx](https://emacsformacosx.com). I can run a build tonight and follow-up with the maintainer of emacsformacosx if need be.

Either way, I'll let you know.

**Comment by vermiculus** [comment]
A build of emacs `--with-modules` works as advertised. Thanks!

**Comment by jjpe** [comment]
Please note that my patch has been merged, so either tonight or tomorrow I'd expect a new Emacs 25.1 build that has the modules functionality already baked in.

**Comment by vermiculus** [comment]
Awesome! I didn't catch that you submitted that PR – thanks!

What a time to be alive…

**Comment by jjpe** [comment]
Yeah it's pretty great :) 

BTW it looks like I was wrong. Apparently the 
 build already exists: https://emacsformacosx.com/download/emacs-builds/Emacs-25.1-1.changes
